### ISSUE TITLE
Validate results for volumes 2454, 2455

### ISSUE THREAD

**Issue by hansvrapi** [HaigeWang1/Paper-Semantification#16]
Check if results after refining the merging step are the as supposed to be for the above volumes.
Focus on:

1.  Is the parsing part executed without any errors? -[x]
2.  Is the paper title correct? -[x]
3.  Are all authors listed as such? -[x]
4.  Do all authors have all their affiliations assigned to them? If not, why is this?
5.  Do all authors have an email adress assigned to them if one is available.

The important part here is to **find solutions** to each of the problems occuring in each question!!

**Comment by BerlinBear997** [comment]
Fixes: 
- Removed additional contents that are not papers (e.g. Front matter: preface, orga, message_kdml, and so on).
- Fixed an error of not finding author information in Cermine/Grobid. Added error handlings when no author information exists in Cermine/Grobid.


- Volume 2455:
Paper 1:
Grobid 100% right.
Cermine stores broken affiliations !!! Author names and their affiliations are mixed and stored in the affiliation attribute.
              Not sure how to fix  it before discussions. Does it count as 20% edge cases?
Paper 3:
Grobid does not link authors with their affiliation keys, so our code does not detect affis.
Cermine has same problem as in paper 1.
Paper 6: 
Grobid has the same problem as in paper 3.
Cermine only stores affiliations once if multiple authors have the same affi.

- Volume 2454:
Paper 2: Cemine does not store authors name correctly, e.g.  Ramin Yahyapour -> min Y
Paper 20: no email from neither Cermine nor Grobid, but in pdf it says firstname.lastname@hpi.de
