### ISSUE TITLE
Validate results: Volumes 2456, 2457

### ISSUE THREAD

**Issue by hansvrapi** [HaigeWang1/Paper-Semantification#17]
Check if results after refining the merging step are the as supposed to be for the above volumes.
Focus on:

- Is the parsing part executed without any errors?
- Is the paper title correct?
- Are all authors listed as such?
- Do all authors have all their affiliations assigned to them? If not, why is this?
- Do all authors have an email adress assigned to them if one is available.
- Do any parsing issues occur?
- The important part here is to find solutions to each of the problems occuring in each question!!

**Comment by HaigeWang1** [comment]
2457
This volume doesn't have grobid or cermine.
Notification of this kind of issue will be added, like "This voulme is lack of grobid and cermine"

**Comment by HaigeWang1** [comment]
2456
In the paper 2, there is department and insitution under the affiliation category, and also address settlement and country.
I have added the way to catch these informations.
